### PR TITLE
Change sysctl from template to sysctl module

### PR DESCRIPTION
**Pull request by JacobBuskirk**
**Overall Review of Changes:**
Changed from configuring sysctl with template to using sysctl module. This also changes it to write to /etc/sysctl.conf instead of overwriting the rhel 8 default symlink at /etc/sysctl.d/99-sysctl.conf

**Issue Fixes:**
#230 

**Enhancements:**
Allows idempotent sysctl tasks

**How has this been tested?:**
Tested against RHEL 8 server

### CODE REVIEW

**Comment by JacobBuskirk** [comment]
I know I've talked with you guys before on the Discord about changing this and auditd to not use these templates, mostly for idempotence reasons, but the current way sysctl is setup is causing issues in my environment. This is because we have configurations in /etc/sysctl.conf, which we we're not really able to change, and overwriting the symlink causes /etc/sysctl.conf to not be loaded in. If you guys don't want to use this, I'll just maintain it separately, but I wanted to at least try to get this merged

**Comment by uk-bolly** [comment]
hi @JacobBuskirk 

Thank you for raising the issue and PR. While we understand your requirement, i wonder if just making the file template output a variable to would improve your stance. Meaning it can be put into any file you need without hitting your current config.
We moved to the template and notify method on all the repositories we maintain into improve the speed on large environments which is significant on clients which, we have running 000's of end points. 

Let us see what we can do to accommodate as many options as possible.

many thanks

uk-bolly

**Comment by JacobBuskirk** [comment]
It doesn't really work for me, since changing the file name would mean that it no longer has precedence over everything else. I get the desire to increase speed, but for sysctl this creates issues. Overwriting the default symlink at /etc/sysctl.d/99-sysctl.conf stops anything in /etc/sysctl.conf from applying, so the right way to do this would be writing to /etc/sysctl.conf. Overwriting the entire /etc/sysctl.conf file also has issues if you have other configurations in it, hence the need to change to the sysctl module.

Like I said I'm also fine with maintaining this separately.

One other thing I wasn't sure how to handle in this, the /etc/sysctl.d/99-sysctl.conf symlink needs recreated. What I have would work for any server where this role would be running for the first time, but if this has been run with the current code then the symlink would have already been overwritten with a file, so it needs added back. Regardless of whether you accept the change from the template to the sysctl module, the role probably shouldn't be overwriting the default /etc/sysctl.d/99-sysctl.conf symlink.

**Comment by uk-bolly** [comment]
hi @JacobBuskirk 

Thank you for the feedback it is always good to get feedback and see how we can adapt. We build and test these systems on completely clean builds where the sysctl.conf is blank.
I have just been testing this and you can rename if you wish rather than amending and still get the precedence.
e.g.
```
* Applying /etc/sysctl.d/99-sysctl.conf ...
* Applying /etc/sysctl.d/99a-sysctl.conf ...
```
This allowed the symlink and a later file to be added ensuring that we keep the system intact.
I hope this helps some way but we will discuss it further here.

thanks again

uk-bolly

**Comment by JacobBuskirk** [comment]
What output do you get if you run sysctl --system? When I have it setup this way it indicates that the symlink takes precedence over /etc/sysctl.d/99a-sysctl.conf
```
ll /etc/sysctl.d/
total 4
-rw-------. 1 root root 2009 Sep 28 16:32 99a-sysctl.conf
lrwxrwxrwx. 1 root root   16 Sep 28 16:32 99-sysctl.conf -> /etc/sysctl.conf

sysctl --system

* Applying /etc/sysctl.d/99a-sysctl.conf ...
kernel.kexec_load_disabled = 1
fs.protected_symlinks = 1
fs.protected_hardlinks = 1
kernel.dmesg_restrict = 1
kernel.perf_event_paranoid = 2
kernel.randomize_va_space = 2
kernel.core_pattern = |/bin/false
net.ipv4.conf.default.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.icmp_echo_ignore_broadcasts = 1
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv4.conf.default.accept_source_route = 0
net.ipv6.conf.default.accept_source_route = 0
net.ipv4.conf.all.forwarding = 0
net.ipv6.conf.all.forwarding = 0
net.ipv6.conf.all.accept_ra = 0
net.ipv6.conf.default.accept_ra = 0
net.ipv4.conf.default.send_redirects = 0
net.ipv4.conf.all.accept_redirects = 0
net.ipv6.conf.all.accept_redirects = 0
kernel.unprivileged_bpf_disabled = 1
kernel.yama.ptrace_scope = 1
kernel.kptr_restrict = 1
user.max_user_namespaces = 0
net.ipv4.conf.all.rp_filter = 1
net.core.bpf_jit_harden = 2
* Applying /etc/sysctl.conf ...
kernel.randomize_va_space = 2
<removed rest of output>
```

**Comment by uk-bolly** [comment]
hi @JacobBuskirk 

I've delved into this further and you are spot on, sysctl.conf is the final file to be loaded in every instance. I can understand why the solution does not work for you.
Let me discuss this further internally, this is indeed interesting way angle. I will see if we can get feedback on from other too on how they manage and maintain these settings.

Thanks again for working with us.

uk-bolly

**Comment by JacobBuskirk** [comment]
@uk-bolly Appreciate you taking a look at it. Just for some more information, we had an issue with our Ansible Automation Platform service, which we ended up putting in a ticket with RedHat for. They found that some settings in /etc/sysctl.conf weren't being applied, and it was RedHat who told us that the /etc/sysctl.d/99-sysctl.conf file on a default install is a symlink to /etc/sysctl.conf. They said we needed to restore the symlink to pull in settings /etc/sysctl.conf.

**Comment by uk-bolly** [comment]
> @uk-bolly Appreciate you taking a look at it. Just for some more information, we had an issue with our Ansible Automation Platform service, which we ended up putting in a ticket with RedHat for. They found that some settings in /etc/sysctl.conf weren't being applied, and it was RedHat who told us that the /etc/sysctl.d/99-sysctl.conf file on a default install is a symlink to /etc/sysctl.conf. They said we needed to restore the symlink to pull in settings /etc/sysctl.conf.

Hi @JacobBuskirk 

I have raised a new branch that has an alternate approach. Using the module as you are but also allowing users to set their own sysctl end point. This is still checked by the audit for both config and running config.
branch: systcl_and_collections (collections change due to galaxy changes and older ansible versions)
Hope this works for you.
Many thanks

uk-bolly

**Comment by JacobBuskirk** [comment]
@uk-bolly Looks like that'll work. Thanks!

**Pull request closed without merging**
