### PR TITLE
Fix typo in SSH_USE_STRONG_RNG

### PR DESCRIPTION
**Pull request by danbarr**
Should be set to 32, not 3

Signed-off-by: Dan Barr <dan@dbarr.com>

### CODE REVIEW

**Comment by uk-bolly** [comment]
Hi @danbarr 

Thank you for raising the PRs for the issue you have seen. This really helps us out with trying to continually improve ansible-lockdown.
Unfortunately as you may have see we have had a couple of issues with the pipeline authentications (still addressing this). Alongside that you may have noticed the issue raised regarding versioning, we have been setting up to relink the content back into ansible-galaxy which has required us to make a lot of necessary changes. This has taken longer than we would have liked.
This has unfortunately has affected the majority of the files and as such will invariably cause conflicts.
We do have the all the required changes merged now but your PRs will undoubtably cause conflicts some where along the way.
Due to these issues and rather than delay your fixes any longer, I will raise new PRs over the next couple of days and hopefully get these live as soon as possible.

Many thanks once again we do appreciate the feedback and hopefully we will have the other issues ironed out over the next couple of days.

Best regards

uk-bolly

**Comment by danbarr** [comment]
Hi @uk-bolly, I'd be happy to rebase my conflicting PRs onto the latest changes in devel if it would save you that work?

**Comment by georgenalen** [comment]
@danbarr,
 I have our updates/changes merged into devel and I created a staging branch based off those latest updates changes. If you can make your updates (rebase and anything else needed) and then PR into the branch staging_pr_16_through20. That branch was created based on the most up to date devel branch and should be good to go.

 Our testing pipeline can only process PR's from directly within the repo, we are working with the vendor that we use for that to help fix it. So hopefully soon this staging thing goes away soon. 

Let us know if you have any issues. Thanks again for working with us. 


George

**Comment by danbarr** [comment]
I just rebased all my PRs off staging_pr_16_through_20 and solved the merge conflicts, all are showing green now.

Dan

**Review by georgenalen — APPROVED** [review]
Looks good

**Pull request merged**
