### PR TITLE
Fixes/rhel 8 010 010150

### PR DESCRIPTION
**Pull request by fbicknel**
hesitantly submitted...

### CODE REVIEW

**Comment by fbicknel** [comment]
I wasn't sure where to put this, so here:
Developer's Certificate of Origin 1.1

By making a contribution to this project, I certify that:

(a) The contribution was created in whole or in part by me and I
    have the right to submit it under the open source license
    indicated in the file; or

(b) The contribution is based upon previous work that, to the best
    of my knowledge, is covered under an appropriate open source
    license and I have the right under that license to submit that
    work with modifications, whether created in whole or in part
    by me, under the same open source license (unless I am
    permitted to submit under a different license), as indicated
    in the file; or

(c) The contribution was provided directly to me by some other
    person who certified (a), (b) or (c) and I have not modified
    it.

(d) I understand and agree that this project and the contribution
    are public and that a record of the contribution (including all
    personal information I submit with it, including my sign-off) is
    maintained indefinitely and may be redistributed consistent with
    this project or the open source license(s) involved.

Signed-off-by: James F Bicknell <fbicknel@gmail.com>

**Comment by georgenalen** [comment]
@fbicknel,
 Thanks for adding in this fix, community contribution is greatly appreciated. I noticed the DCO checks are not passing due to the commit not being signed-off and the commit not being gpg signed. Once these two items are adjusted we can process the PR. 

George

**Comment by fbicknel** [comment]
Thanks, George.... I'll look into that. Sorry... first time out here in the
wild.  :)
<https://about.me/fbicknel?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>
Frank Bicknell
about.me/fbicknel
<https://about.me/fbicknel?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel&utm_content=thumb>Schedule
time with me! <https://calendly.com/fbicknel>

**Comment by georgenalen** [comment]
No worries. There should be some decent how-to's on google with setting up the gpg stuff and how to do the sign-off on past commits. Let me know if getting the past commits sorted is looking really annoying. I can add these changes in on my end and leave a comment about it being from you in the commit/new pr. 

George

**Comment by uk-bolly** [comment]
hi @fbicknel 

As you may have seen we have been going through some big changes, which has affected almost every file in some way, to enable the relinking to ansible galaxy configuration. I hope you don't mind i have incorporated the fix you have provided and it is now in the devel branch.

Hopefully the following links will assist with signed-by and gpg signing your commits
- [GPGsignature](https://docs.github.com/en/github/authenticating-to-github/about-commit-signature-verification) 
- [signed-off-by](https://quicktechrefs.wordpress.com/2018/05/11/git-signed-off-by-flag/)

If you do find any more issues and would like to go through the PR requirements please raise an issue and we will try to assist you.

Best regards

uk-bolly

**Comment by fbicknel** [comment]
Ok; I see the comment above about having already done the change in devel. At least this was good practice.  :)

**Pull request closed without merging**
