### PR TITLE
Updated STIG-ID RHEL-08-040111 to blacklist bluetooth kernel module

### PR DESCRIPTION
**Pull request by matthew-willis**
Signed-off-by: Matthew Willis <matthew.willis@outlook.com>

**Overall Review of Changes:**
Updated STIG-ID RHEL-08-040111 to blacklist bluetooth kernel module

**Issue Fixes:**

Fix Text (F-33151r833335_fix)
--
Configure the operating system to disable the Bluetooth adapter when not in use.Build or modify the "/etc/modprobe.d/bluetooth.conf" file with the following line:install bluetooth /bin/trueDisable the ability to use the Bluetooth kernel module.$ sudo vi /etc/modprobe.d/blacklist.confAdd or update the line:blacklist bluetoothReboot the system for the settings to take effect.

```
Configure the operating system to disable the Bluetooth adapter when not in use.

Build or modify the "/etc/modprobe.d/bluetooth.conf" file with the following line:

install bluetooth /bin/true
Disable the ability to use the Bluetooth kernel module.
$ sudo vi /etc/modprobe.d/blacklist.conf

Add or update the line:blacklist bluetooth

Reboot the system for the settings to take effect.
```

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
@uk-bolly fixed the workflow, if you rebase your branch on devel, then it can be tested in CI again.

**Comment by uk-bolly** [comment]
hi @matthew-willis 

Thanks for picking this up and rebasing and thanks @bbaassssiiee for noticing. 👍 

Regards

uk-bolly

**Comment by matthew-willis** [comment]
> hi @matthew-willis
> 
> Thanks for picking this up and rebasing and thanks @bbaassssiiee for noticing. 👍
> 
> Regards
> 
> uk-bolly

No problem 👍 

Look forward to contributing more in the future!

**Review by uk-bolly — APPROVED** [review]
Nice PR

**Pull request merged**
