### PR TITLE
Spelling corrections.

### PR DESCRIPTION
**Pull request by bbaassssiiee**
Signed-off-by: Bas Meijer <bas.meijer@me.com>

**Overall Review of Changes:**
I fixed small typos in the README file and in two tasks files.

**Issue Fixes:**

**Enhancements:**

**How has this been tested?:**
Reading English.

### CODE REVIEW

**Comment by bbaassssiiee** [comment]
Error message in CI: no matching EC2 VPC found. Is someone looking after that?

**Comment by bbaassssiiee** [comment]
I rebased my branch on devel after @uk-bolly fixed the workflow. Please review...

**Review by uk-bolly — APPROVED** [review]
corrected spelling mistakes and typos 👍

**Comment by uk-bolly** [comment]
> I rebased my branch on devel after @uk-bolly fixed the workflow. Please review...

Thanks @bbaassssiiee for picking this up.

All looks good.

It is merged.

Thanks

uk-bolly

**Pull request merged**
